name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

parameters:
- name: var_group_name
  displayName: Variable group name
  type: string
  default: Common

pool:
  vmImage: $(imageName)

pr:
  branches:
    include:
    - master
    - develop
    - refs/tags/v*
  paths:
    exclude:
    - docs/*
    - README.md

trigger:
  branches:
    include:
    - master
    - develop
    - refs/tags/v*
    - feature/*
  paths:
    exclude:
    - docs/*
    - readme.md

variables:
  - group: Common
  - name: buildConfiguration
    value: 'Release'
  - name: PROJECT
    value: SynkerAPI

strategy:
  matrix:
    linux:
     imageName: 'ubuntu-16.04'

steps:

- task: Bash@3
  displayName: install az devops extension
  inputs:
    targetType: inline
    script: |
      az extension add --name azure-devops

- task: AzureCLI@2
  displayName: Create var
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    azureSubscription: az-synker-sub
    inlineScript: |
      echo $AZ_DEVOPS_PAT | az devops login
      az pipelines variable-group list --org $AZ_DEVOPS_BASE_URL -p $PROJECT
      varGroupId=$(az pipelines variable-group list --org $AZ_DEVOPS_BASE_URL -p $PROJECT --query "[?name=='${{ parameters.var_group_name }}'].id" -o tsv)
      echo $varGroupId
      az pipelines variable-group variable create --id $varGroupId --name "test" --value "testValue" --org $AZ_DEVOPS_BASE_URL -p SynkerAPI

- task: AzureCLI@2
  displayName: Delete var
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    azureSubscription: az-synker-sub
    inlineScript: |
      az pipelines variable-group list --org $AZ_DEVOPS_BASE_URL -p $PROJECT
      varGroupId=$(az pipelines variable-group list --org $AZ_DEVOPS_BASE_URL -p $PROJECT --query "[?name=='${{ parameters.var_group_name }}'].id" -o tsv)
      az pipelines variable-group variable delete --id $varGroupId --name "test"  --org $AZ_DEVOPS_BASE_URL -p $PROJECT --yes


