name: $(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: 'azurepipelines'
      type: 'github'
      name: 'Fazzani/azurepipelines'
      endpoint: 'fazzani'
      ref: refs/tags/v1.0.1

parameters:
- name: sonar_enabled
  displayName: Sonar enabled
  type: boolean
  default: true

pool:
  vmImage: $(imageName)

pr:
  branches:
    include:
    - master
    - develop
    - refs/tags/v*
  paths:
    exclude:
    - docs/*
    - README.md

trigger:
  branches:
    include:
    - master
    - develop
    - refs/tags/v*
  paths:
    exclude:
    - docs/*
    - readme.md

variables:
  - name: buildConfiguration
    value: 'Release'
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: SONAR_PROJECT_KEY
    value: 'gdriveano'
  - name: SONAR_PROJECT_NAME
    value: 'gdriveano'
  - name: SONAR_ORG
    value: fazzani-github
  - name: buildProjects
    value:
      '**/*.csproj'
  - name: testProjects
    value:
      '**/*Tests.csproj'

strategy:
  matrix:
    # linux:
    #  imageName: 'ubuntu-16.04'
    windows:
      imageName: 'windows-2019'
steps:
- template: ci/az-dotnet-core-sonar.yml@azurepipelines
  parameters:
    sonar_enabled: ${{ parameters.sonar_enabled }}
    sonar_project_org: $(SONAR_ORG)
    sonar_project_key: $(SONAR_PROJECT_KEY)
    sonar_project_name: $(SONAR_PROJECT_NAME)
    buildConfiguration: $(buildConfiguration)
    sonar_connection_service: sonarqube
    buildProjects:
      $(buildProjects)
    testProjects:
      $(testProjects)